export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";

export const SEND_PASSWORD_RESET_REQUEST = "SEND_PASSWORD_RESET_REQUEST";
export const SEND_PASSWORD_RESET_ERROR = "SEND_PASSWORD_RESET_ERROR";
export const SEND_PASSWORD_RESET_SUCCESS = "SEND_PASSWORD_RESET_SUCCESS";

export const RESET_AUTH_STATE = "RESET_AUTH_STATE";

export const RESET_STORE_AND_LOG_OUT = "RESET_STORE_AND_LOG_OUT";
